// export const FETCH_CART_REQUEST='FETCH_CART_REQUEST'
// export const FETCH_CART_SUCCESS='FETCH_CART_SUCCESS'
// export const FETCH_CART_FAILURE='FETCH_CART_FAILURE'

// export const SAVE_CART_REQUEST='SAVE_CART_REQUEST'
// export const SAVE_CART_SUCCESS='SAVE_CART_SUCCESS'
// export const SAVE_CART_FAILURE='SAVE_CART_FAILURE'

// export const DELETE_CART_REQUEST='DELETE_CART_REQUEST'
// export const DELETE_CART_SUCCESS='DELETE_CART_SUCCESS'
// export const DELETE_CART_FAILURE='DELETE_CART_FAILURE'

// export const UPDATE_CART_REQUEST='UPDATE_CART_REQUEST'
// export const UPDATE_CART_SUCCESS='UPDATE_CART_SUCCESS'
// export const UPDATE_CART_FAILURE='UPDATE_CART_FAILURE'


export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";