export const FETCH_CUSTOMER__REQUEST = "FETCH_CUSTOMER__REQUEST";
export const FETCH_CUSTOMER__SUCCESS = "FETCH_CUSTOMER__SUCCESS";
export const FETCH_CUSTOMER__FAILURE = "FETCH_CUSTOMER__FAILURE";

export const SAVE_CUSTOMER__SUCCESS = "SAVE_CUSTOMER__SUCCES";

export const DELETE_CUSTOMER__REQUEST = "DELETE_CUSTOMER__REQUEST";
export const DELETE_CUSTOMER__SUCCESS = "DELETE_CUSTOMER__SUCCESS";
export const DELETE_CUSTOMER__FAILURE = "DELETE_CUSTOMER__FAILURE";

export const UPDATE_CUSTOMER__REQUEST = "UPDATE_CUSTOMER__REQUEST";
export const UPDATE_CUSTOMER__SUCCESS = "UPDATE_CUSTOMER__SUCCESS";
export const UPDATE_CUSTOMER__FAILURE = "UPDATE_CUSTOMER__FAILURE";
