export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE='FETCH_PRODUCT_FAILURE'


export const SAVE_PRODUCT_SUCCESS='SAVE_PRODUCT_SUCCES'

export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE='DELETE_PRODUCT_FAILURE'


export const UPDATE_PRODUCT_REQUEST='UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE='UPDATE_PRODUCT_FAILURE'

export const FETCH_PRODUCT_SUCCESS_BY_ID='FETCH_PRODUCT_SUCCESS_BY_ID'